name = 'juso-edge'
compatibility_date = '2021-12-10'
type = 'javascript'
account_id = 'aad5c82543cd1f267b89737d0f56405e'
workers_dev = true

[[kv_namespaces]]
binding = 'INDEX'
id = '0f9a0b3bcd504555b91373dca18fec94'
preview_id = '148ed37fafe24dce984d659acf035b89'

[build]
command = 'yarn esbuild src/worker.ts --bundle --outfile=dist/worker.js --format=esm'

[build.upload]
format = 'service-worker'
