name = 'juso-edge'
compatibility_date = '2021-12-10'
type = 'javascript'
account_id = 'aad5c82543cd1f267b89737d0f56405e'
workers_dev = true

[[kv_namespaces]]
binding = 'INDEX'
id = '0f9a0b3bcd504555b91373dca18fec94'
preview_id = '148ed37fafe24dce984d659acf035b89'

[vars]
LOGFLARE_SOURCE = '1be10ca3-1885-4d6a-8892-d17cf9a2353b'

# [secrets]
# JUSO_CONFIRM_KEY
# LOGFLARE_API_KEY

[build]
command = 'yarn esbuild src/worker.ts --bundle --outfile=dist/worker.mjs --format=esm --conditions=worker'

[build.upload]
format = 'modules'
dir = './dist'
main = './worker.mjs'
